# Generated by Django 4.2.13 on 2024-06-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_user_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
